# Generated by Django 3.2.2 on 2023-06-11 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'asiento',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link_comprobante', models.CharField(default=None, max_length=350)),
            ],
            options={
                'db_table': 'comprobante',
            },
        ),
        migrations.CreateModel(
            name='CondicionImpositiva',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'condicion_impositiva',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.categoria')),
            ],
            options={
                'db_table': 'cuenta',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('condicion_impositiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.condicionimpositiva')),
            ],
            options={
                'db_table': 'entidad',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'moneda',
            },
        ),
        migrations.CreateModel(
            name='Personeria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'personeria',
            },
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tipo_comprobante',
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tipo_identificacion',
            },
        ),
        migrations.CreateModel(
            name='Retenciones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField(default=0)),
                ('unidad', models.CharField(max_length=10)),
                ('ultima_modificacion', models.DateTimeField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.cuenta')),
            ],
            options={
                'db_table': 'retenciones',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_operacion', models.PositiveIntegerField(default='')),
                ('concepto', models.CharField(max_length=150)),
                ('debe', models.FloatField(default=0)),
                ('haber', models.FloatField(default=0)),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_efectiva', models.DateTimeField()),
                ('observaciones', models.CharField(default='', max_length=300)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.asiento')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.comprobante')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.cuenta')),
                ('tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.tipocomprobante')),
            ],
            options={
                'db_table': 'registro',
            },
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=60)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.entidad')),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.tipoidentificacion')),
            ],
            options={
                'db_table': 'identificacion',
            },
        ),
        migrations.AddField(
            model_name='entidad',
            name='personeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.personeria'),
        ),
        migrations.CreateModel(
            name='CuentasAsociadas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cuenta_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuena_asociada_set', to='registros.cuenta')),
                ('cuenta_asociente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_asociente_set', to='registros.cuenta')),
            ],
            options={
                'db_table': 'cuentas_asociadas',
            },
        ),
        migrations.AddField(
            model_name='cuenta',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.entidad'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.moneda'),
        ),
    ]
