# Generated by Django 3.2.2 on 2023-06-18 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='registro',
            name='comprobante',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='registros.comprobante'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo_comprobante',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='registros.tipocomprobante'),
        ),
    ]
