# Generated by Django 3.2.2 on 2023-06-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20230618_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='numero_operacion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
